// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyeqncfolcobgdwodfam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5ZXFuY2ZvbGNvYmdkd29kZmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTc0NDcsImV4cCI6MjA3MzUzMzQ0N30.ATD02d1NQDmD3chaBGfthxHTrJ4M297TrXfMQlI6bt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});